"""StemForge — Specialist Agent.

An evolved agent that uses the domain-specific configuration
produced by the specialization loop.  The specialist's system
prompt contains the full checklist, output schema, and analysis
approach generated by StrategyGenerator + AgentBuilder.
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Dict, List

from stemforge.llm import BaseLLM
from stemforge.models import AgentConfig, Finding


class SpecialistAgent:
    """Domain-specialized agent built from an AgentConfig."""

    def __init__(self, llm: BaseLLM, config: AgentConfig):
        self.llm = llm
        self.config = config

    @classmethod
    def from_file(cls, llm: BaseLLM, config_path: Path) -> "SpecialistAgent":
        """Load an agent from a saved JSON config file."""
        with open(config_path, "r", encoding="utf-8") as f:
            data = json.load(f)
        config = AgentConfig(**data)
        return cls(llm, config)

    def analyze_file(self, filepath: Path) -> List[Finding]:
        """Analyze a single file using the specialist config.

        Parameters
        ----------
        filepath : Path
            Path to the source file.

        Returns
        -------
        list[Finding]
        """
        code = filepath.read_text(encoding="utf-8")
        user_prompt = (
            f"Review this code for security vulnerabilities.\n"
            f"file: {filepath.name}\n\n"
            f"{code}"
        )
        raw = self.llm.call(self.config.system_prompt, user_prompt)
        return self._parse_findings(raw, filepath.name)

    def analyze_directory(self, directory: Path, max_files: int | None = None) -> Dict[str, List[Finding]]:
        """Analyze Python files in a directory.

        Returns
        -------
        dict
            Mapping of ``filename -> list[Finding]``.
        """
        results: Dict[str, List[Finding]] = {}
        files = sorted(directory.glob("*.py"))
        if max_files:
            files = files[:max_files]
        for path in files:
            results[path.name] = self.analyze_file(path)
        return results

    # ------------------------------------------------------------------
    # Parsing helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _parse_findings(raw: str, filename: str) -> List[Finding]:
        """Parse LLM output into Finding objects."""
        try:
            data = json.loads(raw)
        except json.JSONDecodeError:
            m = re.search(r'\{[\s\S]*\}', raw)
            if m:
                try:
                    data = json.loads(m.group())
                except json.JSONDecodeError:
                    return []
            else:
                return []

        findings_raw = data.get("findings", [])
        findings: List[Finding] = []
        for item in findings_raw:
            if isinstance(item, dict):
                item.setdefault("file", filename)
                try:
                    findings.append(Finding(**item))
                except Exception:
                    continue
        return findings
